resource_group_name         = "rg-stg-aks"
region                      = "East US 2"
vnetCIDR                    = ["10.163.0.0/16"]
subnetCIDRs                 = ["10.163.0.0/21"]
environment                 = "staging"
max_node_count              = 4
min_node_count              = 2
node_count                  = 2
node_vm_size                = "Standard_D2_v2"
log_analytics_workspace_name = "aks-loganalyics-ws"
