name: 'AKS Deployment'

on:
  workflow_dispatch:
    #push:
    #  branches: [ main ]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  LOCATION: eastus2
  INFRA_RESOURCE_GROUP: tfstate-resourcegroup
  TF_STATE_STORAGE_ACCOUNT_NAME: tfstatestorage405
  TF_STATE_CONTAINER_NAME: tfstate
  TF_STATE_FILE_NAME: akscluster01.tfstate
  TF_STATE_ACCESS_KEY: "" # will be set later

jobs:
  terraform:
    name: 'Terraform' 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Set short git commit SHA
          id:   commit
          uses: prompt/actions-commit-hash@v2

        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Login to  Azure'
          uses: azure/login@v2   
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}    
        #- name: Login to Azure with SPN
        #  uses: azure/CLI@v2
        #  with:
        #    #azcliversion: 2.28.1
        #    inlineScript: |
        #      az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        - name: Azure CLI script
          uses: azure/CLI@v2
          with:
            #azcliversion: 2.28.1
            inlineScript: |  
              # Create the resource group
              az group create -n $INFRA_RESOURCE_GROUP -l $LOCATION          
              # Create the storage account
              az storage account create -g $INFRA_RESOURCE_GROUP -l $LOCATION \
              --name $TF_STATE_STORAGE_ACCOUNT_NAME \
              --sku Standard_LRS \
              --encryption-services blob
              # Retrieve the storage account key
              ACCOUNT_KEY=$(az storage account keys list --resource-group $INFRA_RESOURCE_GROUP --account-name $TF_STATE_STORAGE_ACCOUNT_NAME --query [0].value -o tsv)
              # Create a storage container (for the Terraform State)
              az storage container create --name $TF_STATE_CONTAINER_NAME --account-name $TF_STATE_STORAGE_ACCOUNT_NAME --account-key $ACCOUNT_KEY

              echo "TF_STATE_ACCESS_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV
              
        - name: Terraform init
          id: init
          run: |
              terraform init \
                -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME" \
                -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                -backend-config="access_key=$TF_STATE_ACCESS_KEY" \
                -backend-config="key=$TF_STATE_FILE_NAME" 
                  
        - name: Terraform validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform plan
          id: plan
          run: terraform plan -no-color

        - name: Terraform apply
          id: apply
          run: terraform apply -auto-approve
