name: 'AKS Deployment'

on:
  workflow_dispatch:
    #push:
    #  branches: [ main ]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  LOCATION: eastus2
  INFRA_RESOURCE_GROUP: tfstate-resourcegroup
  TF_STATE_STORAGE_ACCOUNT_NAME: tfstatestorage405
  TF_STATE_CONTAINER_NAME: tfstate
  TF_STATE_FILE_NAME: akscluster01.tfstate
  TF_STATE_ACCESS_KEY: "" # will be set later

jobs:
  terraform:
    name: 'Terraform' 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Set short git commit SHA
          id:   commit
          uses: prompt/actions-commit-hash@v2

        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Login to  Azure'
          uses: azure/login@v1   
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}    
        #- name: Login to Azure with SPN
        #  uses: azure/CLI@v2
        #  with:
        #    #azcliversion: 2.28.1
        #    inlineScript: |
        #      az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
        - name: Terraform init
          id: init
          run: |
              #set -a 
              #source .env.backend
              terraform init \
                -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME" \
                -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                -backend-config="access_key=$TF_STATE_ACCESS_KEY" \
                -backend-config="key=$TF_STATE_FILE_NAME" 
                  
        - name: Terraform validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform plan
          id: plan
          run: terraform plan -no-color

        - name: Terraform destroy
          id: destroy
          run: terraform destroy -auto-approve
