name: 'AKS Deployment'

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform' 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout out code 
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
       terraform_wrapper: false

    - name: Log in with Azure
      uses: azure/login@v1

    - name: Terraform Init
      #working-directory: aks
      run: terraform init
           
    - name: Terraform Format
      #working-directory: aks
      run: terraform fmt

    - name: Terraform Plan
      #working-directory: aks
      run: terraform plan
    
    - name: Terraform Apply
      #working-directory: aks
      run: terraform apply -auto-approve
