name: Deploy Terraform state backend

on:

  push:
    branches: [ main ]
  #workflow_dispatch:
  #pull_request:
  #  branches:
  #    - master

#permissions:
#  id-token: write
#  contents: read
#  pull-requests: write

jobs:
  deploy:
    name: 'Deploy Terraform state backend'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Set short git commit SHA
        id:   commit
        uses: prompt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Login to  Azure'
        uses: azure/login@v1   
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
            azcliversion: latest
            inlineScript: |  
              set -a 
              source .env.backend
              az account show    
              az group create \
                -l $TF_VAR_location \
                -n $TF_VAR_resource_group_name
              az storage account create \
                -n $TF_VAR_storage_account_name \
                -g $TF_VAR_resource_group_name \
                -l $TF_VAR_location \
                --sku Standard_LRS \
                --allow-blob-public-access false
              az storage container create \
                --name aks \
                --account-name $TF_VAR_storage_account_name

     